[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "de-template"
version = "0.1.0"
description = "A template repo for Data Engineering projects"
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "ruff>=0.12.2",
]
test = [
    "pytest>=8.4.2",
]

[tool.uv]
package = true

[project.scripts]
template = "src.template.main:main"

[tool.mypy]
strict = true
namespace_packages = false
disallow_untyped_defs = true

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing"

[tool.ruff.lint]
select = ["ALL"]
# Remove warnings
ignore = [
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "COM812", # Trailing comma missing
    "T201", # No print statements
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "ARG", # some arguments are unused in tests functions but useful (e.g. mocks)
    "S101", # asserts are OK for tests
    "SLF001" # accessing private members is OK for tests
]

[tool.lint.ruff.pydocstyle]
convention = "google"

[tool.lint.ruff.isort]
known-first-party = ["src"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.lint.bandit]
skips = [
    "B101", # assert used
]
