---
name: Scan Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-container:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scan-container.yml@9fbe4cbba23d4a768eb36462458a4cfcb63682e1 # v5.2.0
    with:
      runtime: python
