---
name: Test Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test-container:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-test-container.yml@5df18d64ab85a164f7241c38447c4575f1a85f40 # v5.1.0
