---
name: Test Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test-container:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-test-container.yml@613a7cc7496ddaed7ae2b12059177d8aeb0760ae # v7.0.0
